<?php
$departmentCourses = array(
    "AGRICULTURE" => array("MBA (Agribusiness)", "B.Sc. (Hons.) Agriculture (Under Self Financing Sc", "M.Sc. (Agriculture) Entomology", "B. Sc. (Hons.) Home Science", "M.Sc.(Home Sc.)", "M.Sc. (Agriculture) Microbiology", "M.Sc. (Agriculture) Plant Pathology", "B.Sc. (Hons) Biochemistry", "M.Sc. Biochemistry", "M.Sc. in Biodiversity Studies & Management", "B.Sc. (Hons) Botany", "M.Sc. Botany"),
    "ARABIC" => array("B.A. (Hons) Arabic", "M.A. (Arabic)"),
    "BENGALI" => array("M.A. (Bengali)"),
    "BIOTECHNOLOGY" => array("M.Sc (Biotechnology)"),
    "BUSINESS ADMINITRATION" => array("Master of Business Administration", "Master of Business Administration (International"),
    "CHEMISTRY" => array("B.Sc. (Hons) Chemistry", "M.Sc. (Chemistry)", "M.Sc. (Industrial Chemistry)"),
    "COMMERCE" => array("B.Com (Hons)", "M.Com", "Master of Financial Management (MFM)", "Master in Human Resource Management (MHRM)", "Master in Insurance & Risk Management (MIRM)", "Master of Tourism & Travel Management (MTTM)"),
    "COMPUTER SCIENCE" => array("B.Sc. (Hons.) Computer Applications", "M.C.A.","M.Sc (Cyber Security)"),
    "ECONOMICS" => array("B.A. (Hons) Economics", "M.A. (Economics)"),
    "EDUCATION" => array("B.Ed.", "B.A. (Hons) Education", "M.A. (Education)", "M.Ed."),
    "ENGLISH" => array("M.A. (English)", "M.A. English Language Teaching (ELT)"),
    "FINE ARTS" => array("B.F.A. (Bachelor of Fine Arts)", "M.F.A. (Master of Fine Arts)"),
    "FOREIGN INDIAN LANGUAGES" => array("B.A. (Hons) Malayalam", "M.A. (Malayalam)", "B.A. (Hons) Persian", "M.A. (Persian)", "B.A. (Hons.) Chinese", "M.A. (Chinese)", "B.A. (Hons.) French", "M.A. (French)", "M.A. (German)", "B.A. (Hons.) Russian", "M.A. (Russian)", "B.A. (Hons.) Spanish", "M.A. (Spanish)", "M.A. (International & West Asian Studies)"),
    "GEOGRAPHY" => array("B.Sc. (Hons) Geography", "M.Sc./M.A. (Geography)"),
    "GEOLOGY" => array("B.Sc. (Hons) Geology", "M.Sc. (Applied Geology)"),
    "HINDI" => array("B.A. (Hindi)","M.A. (Hindi)", "M.A. (Hindi Translation)"),
    "HISTORY" => array("B.A. (Hons) History", "M.A. (History)"),
    "ISLAMIC STUDIES" => array("B.A. (Hons) Islamic Studies", "M.A. (Islamic Studies)"),
    "LAW" => array("LL.M."),
    "LINGUISTICS" => array("M.A. (Language of Advertising Media & Market)", "B.A. (Hons) Linguistics", "M.A. (Linguistics)"),
    "MASS COMMUNICATION" => array("M.A. (Mass Communication)"),
    "MATHEMATICS" => array("B.Sc. (Hons) Mathematics", "M.Sc./M.A. (Mathematics)"),
    "OPERATIONS RESEARCH" => array("M.Sc./MA (Operations Research)"),
    "PHILOSOPHY" => array("M.A. (Philosophy)"),
    "PHYSICAL EDUCATION" => array("Bachelor of Physical Education (B.P.Ed.)", "M.P.Ed."),
    "PHYSICS" => array("B.Sc. (Hons) Physics", "M.Sc. (Physics)"),
    "PLANT PROTECTION" => array("M.Sc. (Agriculture) Plant Pathology"),
    "POLITICAL SCIENCE" => array("M.A. (Human Rights)", "B.A. (Hons) Political Science", "M.A. (Political Science)"),
    "PSYCHOLOGY" => array("B.A. (Hons) Psychology", "M.A. (Psychology)"),
    "PUBLIC ADMINISTRATION" => array("M.A. (Public Administration)"),
    "QURANIC STUDIES" => array("B.A. (Hons) Quranic Studies"),
    "REMOTE SENSING" => array("M.Sc. (Remote Sensing and GIS Application)"),
    "SHIA THEOLOGY" => array("B.A. (Hons.) Shia Theology", "M.A. (Shia Theology)"),
    "SOCIAL WORK" => array("B.A. (Hons.) Social Work", "Master of Social Work"),
    "SOCIOLOGY" => array("B.A. (Hons) Sociology", "M.A. (Sociology)"),
    "STATISTICS" => array("B.Sc. (Hons) Statistics", "M.Sc. / M.A. (Statistics)"),
    "SUNNI THEOLOGY" => array("B.A.Hons.) Sunni Theology", "M.A. (Sunni Theology)"),
    "URDU" => array("M.A. (Urdu)"),
    "WOMEN'S STUDIES" => array("MA (Women's Studies)", "B.A. Women's Studies"),
    "ZOOLOGY" => array("B.Sc. (Hons) Zoology", "M.Sc. Zoology"),
);

// Convert PHP array to JavaScript object
$jsDepartmentCourses = json_encode($departmentCourses);
?>